### ISSUE TITLE
Error when installing with npm

### ISSUE THREAD

**Issue by Tylosten** [cozy/cozy-client#685] opened 2020-04-14 10:31 UTC
The `npm install cozy-client` command fails with error `npm ERR! premature close`.

Error log is saying : `silly fetchPackageMetaData error for minilog@git+https://github.com/cozy/minilog.git#master premature close`

- npm version : 6.13.4
- full error log : [2020-04-14T09_21_28_710Z-debug.log](https://github.com/cozy/cozy-client/files/4474717/2020-04-14T09_21_28_710Z-debug.log)

**Comment by ptbrowne** [comment] 2020-09-02 12:00
Sorry to respond so late.

It looks like a network error. Since the issue is very old and since we haven't had the issue on our side, I am closing. Feel free to reopen if you still have the error.

**Closed by ptbrowne** 2020-09-02 12:00 UTC
