### ISSUE TITLE
DSL : save(document) 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#755] opened 2020-08-10 11:07 UTC
Save currently only takes a document (https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/CozyClient.js#L410). We should be able to provide an array of documents to save and then having an `UPDATE_DOCUMENTS` mutation that execute https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L282 

It'll be faster to use bulk_docs instead :)

It seems that there is no updateAll yet on the PouchLink

**Comment by JF-Cozy** [comment] 2020-08-12 08:48
Same issue here https://github.com/cozy/cozy-client/issues/694 I presume

**Comment by ptbrowne** [comment] 2020-09-02 11:56
Closing since it's a duplicate of #694 .

**Closed by ptbrowne** 2020-09-02 11:56 UTC
Labels: enhancement
